-- Migration 41 : RPC soft_delete_team_member (corbeille membre équipe, admin org role 4)
-- Corrige l'erreur RLS « new row violates row-level security policy for table profiles ».
-- Exécuter : supabase/sql/soft_delete_team_member.sql (fichier complet)
