-- Migration 40 : get_user_edit_details inclut first_name, last_name, username, phone (SECURITY DEFINER)
-- Corrige les fiches dashboard quand RLS bloque la lecture directe de profiles.
-- Exécuter : supabase/sql/get_user_edit_details.sql (fichier complet)
